# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.initrd.luks.devices."luks-f6b7e65c-4aa2-4eaf-9c61-9784ec543dcd".device = "/dev/disk/by-uuid/f6b7e65c-4aa2-4eaf-9c61-9784ec543dcd";

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/c9104185-ee33-432a-840d-a289823d0064";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-46921489-cd5a-4d1a-a5d8-6cd6702995d3".device = "/dev/disk/by-uuid/46921489-cd5a-4d1a-a5d8-6cd6702995d3";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/D4A0-F8B7";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/469c4821-57ba-46a3-a748-c7c5cb7f30a7"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
